version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A main.celery_app worker --loglevel=info -E
    volumes:
      - .:/app
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 50
    depends_on:
      - redis
      - app
